notifications:
  slack: true
  email: false

sudo: required
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install tox-travis
  - pip install numpy scipy # so that scikit-learn can be installed correctly

script:
  - tox
